# #############################################################################
  # Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
  #
  # See the NOTICE file(s) distributed with this work for additional
  # information regarding copyright ownership.
  #
  # This program and the accompanying materials are made available under the
  # terms of the Apache License, Version 2.0 which is available at
  # https://www.apache.org/licenses/LICENSE-2.0.
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  # WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  # License for the specific language governing permissions and limitations
  # under the License.
  #
  # SPDX-License-Identifier: Apache-2.0
  # #############################################################################
---
{{ if index .Values "managed-identity-wallet" "seeding" "enabled" }}
{{- $miwUrl := printf "http://%s" (index .Values "managed-identity-wallet" "miw" "host") -}}
{{- $keycloakUrl := index .Values "managed-identity-wallet" "miw" "keycloak" "url" -}}
{{- $keycloakRealm := index .Values "managed-identity-wallet" "miw" "keycloak" "realm" -}}
{{- $keycloakPath := printf "%s/realms/%s/protocol/openid-connect/token" $keycloakUrl $keycloakRealm -}}
{{- $miwUser := index .Values "managed-identity-wallet" "seeding" "clientId" -}}
{{- $miwSecret := index .Values "managed-identity-wallet" "seeding" "clientSecret" -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-post-install-miw-setup
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "alpine:3.19"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Waiting 30s to start MIW wallet creation..."
              sleep 30
              wget {{ $keycloakPath }} --header 'Content-Type: application/x-www-form-urlencoded' \
              --post-data 'grant_type=client_credentials&client_id={{ $miwUser }}&client_secret={{ $miwSecret }}'
              TOKEN=`cat token | grep -o '"access_token": *"[^"]*"' | sed 's#"access_token":"\(.*\)"#\1#'` && export TOKEN

              {{- range $bpn, $companyName := index .Values "managed-identity-wallet" "seeding" "companies" }}
              wget --header "Content-Type: application/json" --header "Authorization: Bearer $TOKEN" \
              --post-data '{"bpn": "{{ $bpn }}", "name": "{{ $companyName }}"}' "{{ $miwUrl }}/api/wallets" -S -O -
              {{- end }}
{{ end }}
